import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topo from "./componentes/topo";
import Menu from "./componentes/menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='h-dvh grid grid-cols-8 grid-rows-8'>
          <Topo />
          <Menu />
          <div className='col-span-7 row-span-7 p-5 overscroll-contain overflow-y-auto'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
